version: '3.3'

services:
  hotel-reservation-db:
    image: postgres:16-alpine
    restart: always
    environment:
      POSTGRES_DB: hotel_reservation_db
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
    env_file: .env
    ports:
      - "5432:5432"
    volumes:
      - hotel-reservation-db-data:/var/lib/postgresql/data

  car-rental-db:
    image: postgres:16-alpine
    restart: always
    environment:
      POSTGRES_DB: car_rental_db
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
    env_file: .env
    ports:
      - "5433:5432"
    volumes:
      - car-rental-db-data:/var/lib/postgresql/data

  travel-booking-db:
    image: postgres:16-alpine
    restart: always
    environment:
      POSTGRES_DB: travel_booking_db
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
    env_file: .env
    ports:
      - "5434:5432"
    volumes:
      - travel-booking-db-data:/var/lib/postgresql/data

  flight-reservation-db:
    image: postgres:16-alpine
    restart: always
    environment:
      POSTGRES_DB: flight_reservation_db
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
    env_file: .env
    ports:
      - "5435:5432"
    volumes:
      - flight-reservation-db-data:/var/lib/postgresql/data

  mq:
    image: rabbitmq:3-management-alpine
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - mq-data:/var/lib/rabbitmq

volumes:
  hotel-reservation-db-data:
  car-rental-db-data:
  flight-reservation-db-data:
  travel-booking-db-data:
  mq-data:
